services:
  - type: web
    name: scorestream
    runtime: node
    buildCommand: npm install && cd frontend && NODE_ENV=development npm install && npm run build && ls dist/index.html
    startCommand: node backend/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ARCJET_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ARCJET_KEY
        sync: false
      - key: API_FOOTBALL_KEY
        sync: false